# Generated by Django 4.1.6 on 2023-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("sub_genre", models.CharField(blank=True, max_length=20, null=True)),
                ("image", models.TextField()),
                ("page", models.CharField(blank=True, max_length=20, null=True)),
                ("publish", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "books",
                "managed": False,
            },
        ),
    ]
