# Generated by Django 4.2 on 2023-05-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookKo_homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('Books_onsale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookKo_homepage.books')),
            ],
        ),
        migrations.DeleteModel(
            name='Book_Sale',
        ),
    ]
